# .github/workflows/extract_openrouter_cookies.yml
name: Extract OpenRouter Cookies

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'OpenRouter Email Address'
        required: true
        type: string

jobs:
  extract-cookies:
    runs-on: macos-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install seleniumbase

      - name: Install WebDriver (ChromeDriver for UC Mode)
        run: |
          seleniumbase install chromedriver latest

      - name: Run SeleniumBase script to extract cookies
        env:
          OPENROUTER_EMAIL: ${{ github.event.inputs.email }}
          OPENROUTER_PASSWORD: ${{ secrets.OPENROUTER_PASSWORD }} # Still need password secret
        run: |
          # Run directly without proxy
          echo "Running command: pytest extract_cookies.py --uc -s"
          pytest extract_cookies.py --uc -s

      - name: Upload cookies as artifact
        # This step will likely fail if the script fails, which is okay.
        uses: actions/upload-artifact@v4
        with:
          name: openrouter-cookies
          path: openrouter_cookies.json
          if-no-files-found: error
