name: Extract OpenRouter Cookies

on:
  workflow_dispatch: # Allows manual triggering
    inputs:
      email:
        description: 'OpenRouter Email Address'
        required: true
        type: string
      # Removed proxy_type input

jobs:
  extract-cookies:
    runs-on: macos-latest # As requested: Use macOS runner

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install seleniumbase

      - name: Install WebDriver (ChromeDriver for UC Mode)
        run: |
          seleniumbase install chromedriver latest

      - name: Run SeleniumBase script to extract cookies
        env:
          # Pass email from workflow input
          OPENROUTER_EMAIL: ${{ github.event.inputs.email }}
          # Pass password securely from GitHub Secrets
          OPENROUTER_PASSWORD: ${{ secrets.OPENROUTER_PASSWORD }}
          # Removed PROXY environment variables
        run: |
          # Run the pytest script directly without proxy
          echo "Running command: pytest extract_cookies.py --uc -s"
          pytest extract_cookies.py --uc -s

      - name: Upload cookies as artifact
        uses: actions/upload-artifact@v4
        with:
          name: openrouter-cookies
          path: openrouter_cookies.json
          if-no-files-found: error
